name: Junit test and Checkstyle

on: [ push ]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    # ##########################
    # # CHANGE THESE VARIABLES #
    # ##########################
    env:
      Junit_Test_Jar_File: lib/cscd212-s22-lab3.jar

    steps:
      - name: Geting the github project
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get Junit Launcher
        run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.1/junit-platform-console-standalone-1.8.1.jar
        # Used to have the Junit test separate from the project
      #      - name: Getting All The test Jar
      #        run: wget https://github.com/EWU-CSCD212/cscd212-f21-lab8-tztz8/raw/master/cscd212-f21-lab8-tztz8.jar
      - name: Build Code for testing
        run: javac -Xlint:unchecked -cp junit-platform-console-standalone-1.8.1.jar -cp ${{ env.Junit_Test_Jar_File }} -d out/classes $(find src -name '*.java' -not -wholename src/cscd212lab3/Main.java)
      - name: Run junit test (MainTestTA)
        run: java -jar junit-platform-console-standalone-1.8.1.jar --reports-dir=build/test-results/test -cp out/classes -cp ${{ env.Junit_Test_Jar_File }} --select-class=cscd212tests.lab3.MainTestTA

      - name: Run junit test (GameMasterTestTA)
        run: java -jar junit-platform-console-standalone-1.8.1.jar --reports-dir=build/test-results/test2 -cp out/classes -cp ${{ env.Junit_Test_Jar_File }} --select-class=cscd212classes.lab3.GameMasterTestTA

      # post the junit test results
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/test*/TEST*.xml'
      # run and post the checkstyle test
      - name: Run check style info
        uses: nikitasavinov/checkstyle-action@master
        if: always() # always run even if the previous step fails
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          level: info
          tool_name: 'reviewdog-info'
          #checkstyle_config: https://github.com/tztz8/HelloGradle/raw/master/ewu-cscd212.xml
          checkstyle_config: https://github.com/tztz8/HelloGradle/raw/master/ewu-cscd212-info.xml
      - name: Run check style warning
        uses: nikitasavinov/checkstyle-action@master
        if: always() # always run even if the previous step fails
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          level: warning
          tool_name: 'reviewdog-warning'
          #checkstyle_config: https://github.com/tztz8/HelloGradle/raw/master/ewu-cscd212.xml
          checkstyle_config: https://github.com/tztz8/HelloGradle/raw/master/ewu-cscd212-warning.xml
      - name: Run check style error
        uses: nikitasavinov/checkstyle-action@master
        if: always() # always run even if the previous step fails
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          level: error
          tool_name: 'reviewdog-error'
          #checkstyle_config: https://github.com/tztz8/HelloGradle/raw/master/ewu-cscd212.xml
          checkstyle_config: https://github.com/tztz8/HelloGradle/raw/master/ewu-cscd212-error.xml
